### ISSUE TITLE
Notifying sentry about new version does not work

### ISSUE THREAD

**Issue by HGlab01** [ioBroker/testing-action-deploy#3]
I am using the latest version of
https://github.com/ioBroker/ioBroker.example/blob/master/JavaScript/.github/workflows/test-and-release.yml
and tried to configure sentry version notification like this:
```
steps:
      - uses: ioBroker/testing-action-deploy@v1
        with:
          node-version: '14.x'
          # Uncomment the following line if your adapter cannot be installed using 'npm ci'
          # install-command: 'npm install'
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          # When using Sentry for error reporting, Sentry can be informed about new releases
          # To enable create a API-Token in Sentry (User settings, API keys)
          # Enter this token as a GitHub secret (with name SENTRY_AUTH_TOKEN) in the repository options
          # Then uncomment and customize the following block:  
          sentry: true
          sentry-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          sentry-project: "iobroker-followthesun"
          sentry-version-prefix: "iobroker.followthesun"
          # If your sentry project is linked to a GitHub repository, you can enable the following option
          # sentry-github-integration: true
```

Secret is set in the Github reository (I checked that in the meanwhile 100times)
![image](https://user-images.githubusercontent.com/54232526/144458747-6752a126-4479-4aa3-b97a-f20d6b3f35ea.png)

But it results in
![image](https://user-images.githubusercontent.com/54232526/144458899-13c47556-d19a-4fb7-9d0e-82d332e81cce.png)

Parameters looks fine for me:
![image](https://user-images.githubusercontent.com/54232526/144459223-e0b1ff5d-7fff-45a0-aa02-9ade49e434a8.png)

But somehow this "if" does somehting unexpected
https://github.com/ioBroker/testing-action-deploy/blob/46ec040ae7b3adc54d6c27051cb3949c26d81dbe/action.yml#L119

Any ideas?
Script run is available here
https://github.com/HGlab01/ioBroker.followthesun/runs/4397350477

I tried it out for two adapters (followthesun and tado) with the same result.
@DutchmanNL had also a quick look on it. We both are struggling ;-)

Thanks for your support!
