### ISSUE TITLE
Add documentation for required Workflow permissions

### ISSUE THREAD

**Issue by klein0r** [ioBroker/testing-action-deploy#4]
After running this action in a new repo, I've received "Resource not accessible by integration".

I had to enable this option. Maybe this should be added to the documentation?

<img width="1039" alt="Screenshot 2022-04-29 at 12 59 12" src="https://user-images.githubusercontent.com/1959049/165932281-2930b0c2-1b31-49b1-8a8b-f7c3a89db797.png">

**Comment by AlCalzone** [comment]
Maybe the preferable solution would be to request the permissions at the action level (in the workflow .yml):
https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/

Would you be willing to help out with this?

**Comment by klein0r** [comment]
> Has Github's default for this somehow changed? This is how it looks like for me and I didn't touch anything:

Seems so, I've created a repository today and the screenshot above are the default settings.
(I can't remember that I've changed that setting for my other repos)

**Comment by klein0r** [comment]
> Would you be willing to help out with this?

I'm not an expert for GitHub actions and never created an own action - but let me know if I can help. Seems like the user has to add the permissions to the yml file. Like this?

```yml
  # Deploys the final package to NPM
  deploy:
    needs: [check-and-lint, adapter-tests]

    # Trigger this step only when a commit on any branch is tagged with a version number
    if: |
      contains(github.event.head_commit.message, '[skip ci]') == false &&
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: ioBroker/testing-action-deploy@v1
        with:
          node-version: '14.x'
          # Uncomment the following line if your adapter cannot be installed using 'npm ci'
          # install-command: 'npm install'
          build: true
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
